---
galaxy_info:
  author: Nimrod Adar
  description: Apache
  company: Shore technologies
  license: MIT
  min_ansible_version: 2.3
  platforms:
  - name: Debian
    versions:
    - stretch
    - jessie
  - name: Ubuntu
    versions:
    - xenial
    - trusty
  galaxy_tags: [ web ]
dependencies:
- src: adarnimrod.ca-store
  name: ca-store
